name: story_craft
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  fpdart: ^1.2.0
  get_it: ^8.0.3
  google_fonts: ^8.0.2
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_ios_android_11.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/play-store-icon-launcher.png"