// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// ////
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC95ZvhflXnTbNEBDzOkf8Yd1zXaShdi0',
    appId: '1:662555295980:web:805a3689f3b378739fe5c9',
    messagingSenderId: '662555295980',
    projectId: 'story-book-9a330',
    authDomain: 'story-book-9a330.firebaseapp.com',
    storageBucket: 'story-book-9a330.firebasestorage.app',
    measurementId: 'G-GZCJZK4G6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPGm1rdUSXP2GhfQ6SnSBZn3xrixKxjtw',
    appId: '1:662555295980:android:867f356540dfaab29fe5c9',
    messagingSenderId: '662555295980',
    projectId: 'story-book-9a330',
    storageBucket: 'story-book-9a330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcpjpnQSqmqYvqSzG07Ak68e_X12lJFM',
    appId: '1:662555295980:ios:5a4906aabaa17db69fe5c9',
    messagingSenderId: '662555295980',
    projectId: 'story-book-9a330',
    storageBucket: 'story-book-9a330.firebasestorage.app',
    iosClientId:
        '662555295980-n08mv609612d41j8rc97qlmp1kft19pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.storyCraft',
  );
}
